/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TipsResponseMsg'
 * message type.
 */

package MsgClass;

public class TipsResponseMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 11;

    /** Create a new TipsResponseMsg of size 4. */
    public TipsResponseMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TipsResponseMsg of the given data_length. */
    public TipsResponseMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TipsResponseMsg with the given data_length
     * and base offset.
     */
    public TipsResponseMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TipsResponseMsg using the given byte array
     * as backing store.
     */
    public TipsResponseMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TipsResponseMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TipsResponseMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TipsResponseMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TipsResponseMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TipsResponseMsg embedded in the given message
     * at the given base offset.
     */
    public TipsResponseMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TipsResponseMsg embedded in the given message
     * at the given base offset and length.
     */
    public TipsResponseMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TipsResponseMsg> \n";
      try {
        s += "  [tipHash_1=0x"+Long.toHexString(get_tipHash_1())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [tipHash_2=0x"+Long.toHexString(get_tipHash_2())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: tipHash_1
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'tipHash_1' is signed (false).
     */
    public static boolean isSigned_tipHash_1() {
        return false;
    }

    /**
     * Return whether the field 'tipHash_1' is an array (false).
     */
    public static boolean isArray_tipHash_1() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'tipHash_1'
     */
    public static int offset_tipHash_1() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'tipHash_1'
     */
    public static int offsetBits_tipHash_1() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'tipHash_1'
     */
    public int get_tipHash_1() {
        return (int)getUIntBEElement(offsetBits_tipHash_1(), 16);
    }

    /**
     * Set the value of the field 'tipHash_1'
     */
    public void set_tipHash_1(int value) {
        setUIntBEElement(offsetBits_tipHash_1(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'tipHash_1'
     */
    public static int size_tipHash_1() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'tipHash_1'
     */
    public static int sizeBits_tipHash_1() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: tipHash_2
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'tipHash_2' is signed (false).
     */
    public static boolean isSigned_tipHash_2() {
        return false;
    }

    /**
     * Return whether the field 'tipHash_2' is an array (false).
     */
    public static boolean isArray_tipHash_2() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'tipHash_2'
     */
    public static int offset_tipHash_2() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'tipHash_2'
     */
    public static int offsetBits_tipHash_2() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'tipHash_2'
     */
    public int get_tipHash_2() {
        return (int)getUIntBEElement(offsetBits_tipHash_2(), 16);
    }

    /**
     * Set the value of the field 'tipHash_2'
     */
    public void set_tipHash_2(int value) {
        setUIntBEElement(offsetBits_tipHash_2(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'tipHash_2'
     */
    public static int size_tipHash_2() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'tipHash_2'
     */
    public static int sizeBits_tipHash_2() {
        return 16;
    }

}
