SUBDIRS = DAG MsgClass

ROOT = ../../../support/sdk/java/

include $(ROOT)/Makefile.include


#JAVADOCDIR = ../../../doc/javadoc

#fullnode.jar: all
#	rm -f fullnode.jar
#	@# create the jar, as update requires it to exist. we use a
#	@# .class file we assume always exists
#	find . | grep -E "class|jpg|gif" | xargs jar cf fullnode.jar

